### ISSUE TITLE
Be able to recover resources for a single component without updating the whole store

### ISSUE THREAD

**Issue by jsmrcaga** [BenjaminVanRyseghem/switchless-redux-actions#2]
### Objective
Recover a network resource in a component without passing by the redux store

### Problem
To recover a resource from the network, we currently go through Redux API middleware plain objects which will update the whole redux store, inducing a re-render of the whole app.

### Solution 
Create single API provider which uses `Connect`  to get the token and create a network request without triggering a state update

**Comment by BenjaminVanRyseghem** [comment]
We do not want to maintain state outside of the store.

If you have data that should not affect your app rendering, then why fetching it?

Moreover, React is made to optimize this kind of rendering, so it's usually not an issue to update props.
